version: "2"  # Use version 2 of the Docker Compose file format
services:
  tpcaog:
    image: app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./VOLUMES/tpcaog:/usr/app/web/users
    command: ["node", "./app/_cmd_server.js",  "-p", "3000"]
  
  jkpan:
    image: app
    ports:
      - "3001:3000"
    volumes:
      - ./VOLUMES/jkpan:/usr/app/web/users
    command: ["node", "./app/_cmd_server.js",  "-p", "3000", "-auth"]


# container_name: jkpan
#build: . 
#environment:
#  - NODE_ENV=production
#networks:
#  - mynetwork
