version: 'version: 2'  # Use version 2 of the Docker Compose file format
services:
  app:
    image: myapp:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/usr/src/app
    networks:
      - mynetwork